---
apiVersion: v1
data:
  kServeServerless: disabled
  oauthProxyImage: quay.io/openshift/origin-oauth-proxy:4.14.0
  trustyaiOperatorImage: quay.io/trustyai/trustyai-service-operator:latest
  trustyaiServiceImage: quay.io/trustyai/trustyai-service:latest
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/part-of: trustyai
  name: trustyai-service-operator-config
