---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: trustyai-service-operator
    app.kubernetes.io/instance: metrics-reader
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: trustyai
  name: trustyai-service-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
