---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: trustyai-service-operator
    app.kubernetes.io/instance: proxy-rolebinding
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: trustyai
  name: trustyai-service-operator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trustyai-service-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: trustyai-service-operator-controller-manager
  namespace: {{ .Release.Namespace }}
