apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: trustyai-service-operator
    app.kubernetes.io/part-of: trustyai
  name: trustyai-service-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trustyai-service-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: trustyai-service-operator-controller-manager
    namespace: {{ .Release.Namespace }}
